components:
  requestBodies:
    Sas:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Page'
  schemas:
    BadRequest:
      description: Parameter validation failed
      properties:
        msg:
          type: string
      type: object
    Page:
      properties:
        id:
          type: string
      type: object
info:
  description: Demo API
  title: Demo API
  version: 1.0.0
openapi: 3.0.1
paths:
  /page/{id}:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'
          description: Page found
        400:
          content:
            apllication/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
          description: Parameter validation fail
        404:
          description: Object not found
